apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-filter
  namespace: kevin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs-filter
  template:
    metadata:
      labels:
        app: logs-filter
    spec:
      containers:
        - name: app
          image: docker.fast.ar/logs-filter:latest
          env:
          - name: APP
            value: logs-filter
      imagePullSecrets:
        - name: regcred