apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logger-role
  namespace: kevin
rules:
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logger-role-binding
  namespace: kevin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logger-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kevin