---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-fast-ar
  namespace: kevin
spec:
  secretName: api-fast-ar-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - api.fast.ar
---
