---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-fast-ar
  namespace: default
spec:
  secretName: docker-fast-ar-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - docker.fast.ar
---
