---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ez-ar
  namespace: minecraft
spec:
  secretName: ez-ar-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - ez.ar
---
