apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: minecraft
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
    - name: tcp
      port: 25565
      targetPort: 25565
      nodePort: 30000
      protocol: TCP
    - name: udp
      port: 25565
      targetPort: 25565
      nodePort: 30000
      protocol: UDP