apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: kevin
spec:
  replicas: 10
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: app
          image: docker.fast.ar/go-server
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: regcred