apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k3s-fast-ar
  namespace: default
spec:
  secretName: k3s-fast-ar-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - k3s.fast.ar